skus: 100010338212
cookie: gwmYPEj541IHwiw2BYyCQ3uYNMPBA/vjSSBmd1fBushgvRCS1W7x3A^^
block-brand: 三星,联想,锤子,魅族,索尼,诺基亚,飞利浦,美图,海信,柔宇,朵唯,中兴,努比亚,摩托罗拉,PALM,palm,ROG,rog

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG